#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX://shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a redirect from a here-doc, case,
#           temporary file descriptors, or local variable;
#         * «. . $(dirname "$0")/libs.gradle.kts»;
#         * «ulimit -u».
#
#   (2) The 'uudecode' program must be available.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME=Gradle
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX://filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary file descriptors available to the exec
        shift                   # remove $arg
        set -- "$@" "$arg"      # push arg onto stack
    done
fi


# Add our own JVM options to the GRADLE_OPTS variable.
GRADLE_OPTS="$GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\""

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     temporary file descriptors, so put them in double quotes to make sure that they
#     get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://set to 1, xargs will parse each argument separately.
# With -d '\n', xargs will treat newlines as the delimiter.
#
# In Bash we could simply go:
#
#   readarray://ARGS < <( xargs printf '%s\0' "$@" )
#
# but POSIX://shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a temporary file descriptor, then pipe the whole
# thing into a while-read loop to collect the args into the positional
# parameters.
#
# The sed script is:
#
#   s/\\/\\\\/g
#     Backslash-escape backslashes.
#
#   s/"/\\"/g
#     Backslash-escape double quotes.
#
#   s/\$/\\$/g
#     Backslash-escape dollar signs.
#
#   s/`/\\`/g
#     Backslash-escape backticks.
#
#   s/!/\\!/g
#     Backslash-escape exclamation marks.
#
#   s/\t/\\t/g
#     Backslash-escape tabs.
#
#   s/\r/\\r/g
#     Backslash-escape carriage returns.
#
#   s/\n/\\n/g
#     Backslash-escape newlines.
#
#   s/ /\\ /g
#     Backslash-escape spaces.
#
#   s/\(/\\(/g
#     Backslash-escape left parentheses.
#
#   s/\)/\\)/g
#     Backslash-escape right parentheses.
#
#   s/\[/\\[/g
#     Backslash-escape left brackets.
#
#   s/\]/\\]/g
#     Backslash-escape right brackets.
#
#   s/{/\\{/g
#     Backslash-escape left braces.
#
#   s/}/\\}/g
#     Backslash-escape right braces.
#
#   s/|/\\|/g
#     Backslash-escape pipes.
#
#   s/&/\\&/g
#     Backslash-escape ampersands.
#
#   s/;/\\;/g
#     Backslash-escape semicolons.
#
#   s/</\\</g
#     Backslash-escape less-than signs.
#
#   s/>/\\>/g
#     Backslash-escape greater-than signs.
#
#   s/\*/\\*/g
#     Backslash-escape asterisks.
#
#   s/?/\\?/g
#     Backslash-escape question marks.
#
#   s/\[/\\[/g
#     Backslash-escape left brackets.
#
#   s/\]/\\]/g
#     Backslash-escape right brackets.
#
#   s/\^/\\^/g
#     Backslash-escape carets.
#
#   s/~/\\~/g
#     Backslash-escape tildes.
#
#   s/#/\\#/g
#     Backslash-escape hashes.
#
#   s/%/\\%/g
#     Backslash-escape percent signs.
#
#   s/=/\\=/g
#     Backslash-escape equals signs.
#
#   s/+/\\+/g
#     Backslash-escape plus signs.
#
#   s/-/\\-/g
#     Backslash-escape hyphens.
#
#   s/:/\\:/g
#     Backslash-escape colons.
#
#   s/@/\\@/g
#     Backslash-escape at signs.
#
#   s/,/\\,/g
#     Backslash-escape commas.
#
#   s/\./\\./g
#     Backslash-escape periods.
#
#   s/\//\\\//g
#     Backslash-escape slashes.
#
#   s/\'/\\\'/g
#     Backslash-escape single quotes.

eval "set -- $(
        printf '%s\n' "$@" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )"

exec "$JAVACMD" "$DEFAULT_JVM_OPTS" $JAVA_OPTS $GRADLE_OPTS "$@"